name: Step Types

on:
  workflow_dispatch: 

jobs:
  say-hello-in-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi Hello World"
  say-hello-in-python:
    runs-on: ubuntu-20.04   
    steps:
      - run: print("Hello World")
        shell: python
