name: in-action

on:
  push: 

jobs:
  say-hello-in-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi Hello World"
  say-hello-in-python:
    runs-on: ubuntu-latest  
    steps:
      - run: print("Hello World")
        shell: python
  say-hello-in-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "from action in the github"
        
